#!/bin/sh

version={etcd_shell_version}

init() {
    echo "This is etcd shell version, welcome!"
}

usage() {
	echo "usage: etcd version"
	echo "功能说明:"
    echo "  显示etcd脚本程序版本"
}

cmd_help() {
	usage
	exit 0
}

cmd_default() {
	echo $version
}