#!/bin/sh

init() {
    echo "This is etcd add shell, welcome!"
    export CURRENT_DIR=$PWD
}

usage() {
    echo "usage: etcd add <options>"
    echo "功能说明:"
    echo "  增加目录或者文件"
    echo "参数说明:"

}

cmd_help() {
    usage
    exit 0
}

cmd_default() {
    echo "function cmd_default."
}

