#!/bin/sh

init() {
    echo "This is etcd delete shell, welcome!"
    export CURRENT_DIR=$PWD
}

usage() {
    echo "usage: etcd delete <options>"
    echo "功能说明:"
    echo "  删除目录或者文件"
    echo "参数说明:"
    echo "	-u	必选参数: url, 指定其请求url包含全路径. 例如: http://172.18.2.164:2379/v2/keys/dev/yangtao ."

}

cmd_help() {
    usage
    exit 0
}

cmd_default() {
    echo 函数cmd_default执行开始 ...
	DEFINE_string	url		''		'url'		u

	FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"

    echo 验证输入参数 -u ...
    if [ "${FLAGS_url}" = "" ]; then
        usage
        die "错误信息: -u 是必选参数."
    fi

    curl ${FLAGS_url} -XDELETE

}
