#!/bin/sh

init() {
    echo "This is etcd update shell, welcome!"
    export CURRENT_DIR=$PWD
}

usage() {
    echo "usage: etcd update <options>"
    echo "功能说明:"
    echo "  修改目录或者文件"
    echo "参数说明:"
    echo "	-u	必选参数: url, 指定其请求url包含全路径. 例如: http://172.18.2.164:2379/v2/keys/dev/yangtao ."
    echo "	-m	必选参数: mode, 指定其模式. 值类型: dir | key. 默认值key . "
    echo "	-v	可选参数: value, 指定其值. 若mode=key时必须指定其值，mode=directory时可选 ."

}

cmd_help() {
    usage
    exit 0
}

cmd_default() {
    echo 函数cmd_default执行开始 ...
	DEFINE_string	url		''		'url'		u
    DEFINE_string	mode	'key'	'mode'		m
    DEFINE_string	value	''		'value'		v

    FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"

    echo 验证输入参数 -u ...
    if [ "${FLAGS_url}" = "" ]; then
        usage
        die "错误信息: -u 是必选参数."
    fi

    echo 开始处理...
    if [ "${FLAGS_mode}" = "key" ]; then
    	echo 验证参数 -v ...
    	if [ "${FLAGS_value}" = "" ]; then
        	usage
        	die "错误信息: -k值为key时 -v是必选参数."
    	fi

    	echo Changing the value of a key ...
    	curl ${FLAGS_url} -XPUT --data-urlencode "value=${FLAGS_value}"
    else
    	echo Not support to changing directories ...
    fi
}
